export const EDIT_LIST = 'EDIT_LIST';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const CREATE_LIST = 'CREATE_LIST';
export const FIND_TO_NAME = 'FIND_TO_NAME';
export const FILTER_LIST = 'FIND_TO_NAME';
export const GETTING_PRODUCTS = 'GETTING_PRODUCTS' ;
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FIRTS_RENDER_PUTHNAME = 'FIRTS_RENDER_PUTHNAME';
export const FIND_TO_NAME_PATHNAME = 'FIND_TO_NAME_PATHNAME';






